#!/bin/bash

#### This is the compiler driver ####
#
# GCC is used for preproccesing, assembling, and linking.

INPUT_FILE=$1

if [[ -z $INPUT_FILE ]]; then
  echo "No input file specified"
  exit 1
fi

# Preproccesor
PREPROCCESOR_FILE="${INPUT_FILE%?}i"
gcc -E -P $INPUT_FILE -o $PREPROCCESOR_FILE

# Compiler
bin/compiler $PREPROCCESOR_FILE
rm $PREPROCCESOR_FILE

# Assembler and Linker
# gcc ASSEMBLY_FILE -o OUTPUT_FILE
# rm ASSEMBLY_FILE
