#!/bin/bash
set -e

#### This is the compiler driver ####
#
# GCC is used for preproccesing, assembling, and linking.

INPUT_FILE=$1
if [[ -z $INPUT_FILE ]]; then
  echo "No input file specified"
  exit 1
fi

set_input_file ()
{
  INPUT_FILE=$1
  if [[ -z $INPUT_FILE ]]; then
    echo "No input file specified"
    exit 1
  fi
}

case $INPUT_FILE in
  "--lex")
  COMPILER_STAGE_OPTION=0
  set_input_file $2
  ;;
  "--parse")
  COMPILER_STAGE_OPTION=1
  set_input_file $2
  ;;
  "--codegen")
  COMPILER_STAGE_OPTION=2
  set_input_file $2
  ;;
  *)
  COMPILER_STAGE_OPTION=3
  ;;
esac

# Move to compiler dir
PARENT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P)
cd $PARENT_PATH

# Preproccesor
PREPROCCESOR_FILE="${INPUT_FILE%?}i"
gcc -E -P $INPUT_FILE -o $PREPROCCESOR_FILE

# Compiler - don't run tests
./bin/compiler $PREPROCCESOR_FILE --no-run
rm $PREPROCCESOR_FILE

# Assembler and Linker
# gcc ASSEMBLY_FILE -o OUTPUT_FILE
# rm ASSEMBLY_FILE
